# import = ['C:\dev\alacritty-master\catppuccin.toml']
live_config_reload = true
working_directory = "C:\\"

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14.0

[font.bold]
family = "MesloLGLDZ Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGLDZ Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGLDZ Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGLDZ Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "Back"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

# [[keyboard.bindings]]
# action = "ToggleFullscreen"
# key = "J"
# mods = "Control|Alt"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
args = ["-i", "-l"]
program = "C:/Program Files/Git/bin/bash.exe"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_title = false
opacity = 0.95
startup_mode = "Maximized" # startup_mode = "Fullscreen"
title = "Alacritty"
